import { test, expect } from "@playwright/test";
import { snapshot, seed } from "./qa-phoneSnapshot";
for (const width of [360,760]) for (const count of [2,12]) {
  test(`phone reveal and states: ${width}px / ${count} players / ${seed}`, async ({page}, info) => {
    await page.setViewportSize({width,height:800});
    await page.emulateMedia({reducedMotion:"reduce"});
    let current = snapshot(count);
    await page.addInitScript(() => {
      localStorage.setItem("mindbattle-network-credentials-v1", JSON.stringify([{code:"1234", token:"qa-fixture",role:"player"}]));
      localStorage.setItem("mindbattle-network-preferences-v1", JSON.stringify({volume:0,muted:true,textSize:"normal",highContrast:false,reducedMotion:true}));
    });
    await page.route("**/api/network/stream?*", route => route.fulfill({contentType:"text/event-stream", body:`event: connected\ndata: {"generation":1}\n\ndata: ${JSON.stringify(current)}\n\n`}));
    await page.route("**/api/network/heartbeat?*", route => route.fulfill({json:{ok:true}}));
    await page.goto("/network?muted=1");
    await expect(page.locator(".network-reserve")).toBeVisible();
    await expect(page.locator(".network-reserve")).toContainText("Запас времени");
    await expect(page.locator(".network-reserve strong")).toHaveText("60 с");
    await expect(page.locator(".network-cards")).not.toContainText("Запас");
    expect(await page.locator(".network-reserve strong").evaluate(el => parseFloat(getComputedStyle(el).fontSize))).toBeGreaterThanOrEqual(32);
    await expect(page.locator(".network-explanation > p")).toHaveCount(1);
    await expect(page.locator(".network-explanation > p")).toContainText("Основное объяснение раскрывается");
    await expect(page.locator(".network-explanation .wrong-answer-notes article")).toHaveCount(3);
    await expect(page.locator(".network-explanation .wrong-answer-notes")).not.toContainText("Верный вариант");
    await expect(page.locator(".wrong-answer-notes > strong")).toHaveCount(0);
    await expect(page.locator(".network-answers .wrong")).toHaveCount(count === 2 ? 0 : 3);
    await expect(page.locator(".network-answers small").first()).toContainText("Александр 1");
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({path:info.outputPath(`${seed}-reveal-${width}-${count}.png`),fullPage:true});
    current = {...current, view: {...current.view!, teams: current.view!.teams.map(card => ({...card, reserveMs:12_000}))}};
    await page.reload();
    await expect(page.locator(".network-reserve strong")).toHaveText("12 с");
    current = {...current, phase:"standings", revealedChoices:undefined, view:{...current.view!,phase:"standings",question:undefined,standings:current.players.map((p,index)=>({teamId:p.id,rank:p.departed ? 0 : 1,score:100,correct:1,incorrect:2,noAnswer:1}))}};
    await page.reload();
    await expect(page.locator(".network-standings tbody > tr")).toHaveCount(count);
    await expect(page.locator(".network-standing--self")).toContainText("Александр 1 Константинопольский · Вы");
    await expect(page.locator(".network-standings")).toContainText("Выбыл");
    await expect(page.locator(".network-cards")).toHaveCount(0);
    await expect(page.getByRole("columnheader", {name:"Правильные ответы", exact:true})).toBeVisible();
    await expect(page.locator(".network-standings thead th")).toHaveCount(5);
    await expect(page.locator(".network-standing--self td").last()).toHaveText("3");
    const rowHeights = await page.locator(".network-standings tbody > tr").evaluateAll(rows => rows.map(row => row.getBoundingClientRect().height));
    expect(Math.max(...rowHeights)).toBeLessThan(80);
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({path:info.outputPath(`results-table-v3-standings-${width}-${count}.png`),fullPage:true});
    current = {...current, phase:"bonus-veto", canVeto:true, titles:{topic:"История науки",other:"Мировая культура",third:"География"},view:{...current.view!,phase:"bonus-veto",standings:undefined,topicCandidates:["topic","other","third"]}};
    await page.reload();
    await expect(page.locator(".network-turn-status--required")).toHaveText("Выберите тему, которую хотите исключить");
    await expect(page.locator(".network-topics button").first()).toBeEnabled();
    await page.screenshot({path:info.outputPath(`${seed}-veto-action-${width}-${count}.png`),fullPage:true});
    current = {...current, ownVeto:"topic",vetoes:[{playerId:current.selfId!,name:current.leaderName,topicId:"topic"}]};
    await page.reload();
    await expect(page.locator(".network-turn-status--waiting")).toContainText("Вы исключили «История науки»");
    await expect(page.getByRole("button",{name:"Снять запрет",exact:true})).toBeEnabled();
    await expect(page.locator(".network-topics button").nth(1)).toBeEnabled();
    await page.screenshot({path:info.outputPath(`${seed}-veto-confirmed-${width}-${count}.png`),fullPage:true});
    current = {...current, canVeto:false, ownVeto:undefined};
    await page.reload();
    await expect(page.locator(".network-turn-status--waiting")).toHaveText("Другие игроки исключают темы. Вы ждёте");
    for (const button of await page.locator(".network-topics button").all()) await expect(button).toBeDisabled();
  });
}
